export {
  BaseVideoResponseDto,
  DataVideo,
  VideoCommentRequestDto,
  VideoCommentResponseDto,
  CreateReactionRequestDto,
  CreateReactionResponseDto,
  CreateCommentReactionRequestDto,
  CreateCommentReactionResponseDto,
  BaseVideoCommentResponseDto,
  VideosLiveResponseDto,
  VideosOfflineResponseDto,
  AddVideoViewRequestDto,
  AddVideoViewResponseDto,
  GetSimilarVideosResponseDto,
} from 'shared/build';
