const DARK_THEME_BASE_COLOR = '#1f222a';
const DARK_THEME_HIGHLIGHT_COLOR = '#474747';
const LIGHT_THEME_BASE_COLOR = '#ebefe8';
const LIGHT_THEME_HIGHLIGHT_COLOR = '#ffffff';

export { DARK_THEME_BASE_COLOR, DARK_THEME_HIGHLIGHT_COLOR, LIGHT_THEME_BASE_COLOR, LIGHT_THEME_HIGHLIGHT_COLOR };
