const LIGHT_THEME_TOOLTIP_BACKGROUND_COLOR = '#c3cfc0';
const DARK_THEME_TOOLTIP_BACKGROUND_COLOR = '#000000';
const DARK_THEME_TOOLTIP_TEXT_COLOR = '#ffffff';
const LIGHT_THEME_TOOLTIP_TEXT_COLOR = '#000000';

export {
  LIGHT_THEME_TOOLTIP_TEXT_COLOR,
  LIGHT_THEME_TOOLTIP_BACKGROUND_COLOR,
  DARK_THEME_TOOLTIP_BACKGROUND_COLOR,
  DARK_THEME_TOOLTIP_TEXT_COLOR,
};
