version: '3.9'
services:
  rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"
    container_name: rtmp
    depends_on:
      - backend
    networks:
      - backend_network
    volumes:
      - ../../nginx/nginx.rtmp.conf:/etc/nginx/nginx.conf
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbit
    networks:
      - backend_network
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
  api-db:
    image: postgres:14
    container_name: api-db
    ports:
      - '5432:5432'
    volumes:
      - pgdata_api:/var/lib/postgresql/data
      - pgconf_api:/etc/postgresql
      - pglog_api:/var/log/postgresql
    env_file:
      - ../../.env/api-db.env
    networks:
      - backend_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  backend:
    container_name: backend
    build:
      context: ../../
      dockerfile: .docker/debug/backend-debug.Dockerfile
    depends_on:
      - api-db
    ports:
      - '5001:5001'
    env_file:
      - ../../.env/api-debug.env
    volumes:
      - ../../backend/core:/app/backend/core
      - node_modules_backend:/app/backend/core/node_modules:rw
      - node_modules_backend_shared:/app/shared/node_modules:rw
    networks:
      - backend_network
      - frontend_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  push:
    image: push
    container_name: push
    depends_on:
      - rabbitmq
    ports:
      - '5002:5002'
    env_file:
      - ../../.env/push.env
    networks:
      - backend_network
      - frontend_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  video-transcoding-server:
    image: video-transcoding-server
    container_name: video-transcoding-server
    volumes:
      - ../../playback:/app/backend/video-transcoding-server/playback:rw
    depends_on:
      - rabbitmq
    ports:
      - '5003:5003'
    env_file:
      - ../../.env/video-transcoding-server.env
    networks:
      - backend_network
      - frontend_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  frontend:
    build:
      context: ../../
      dockerfile: .docker/debug/frontend-debug.Dockerfile
    container_name: frontend
    depends_on:
      - backend
    env_file:
      - ../../.env/client-debug.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ../../frontend:/app/frontend
      - ../../playback:/assets/segments:ro
      # - node_modules_frontend:/app/frontend/node_modules:rw
      # - node_modules_frontend_upper:/app/node_modules:rw
      # - node_modules_frontend_shared:/app/shared/node_modules:rw
    networks:
      - backend_network
      - frontend_network
  nginx:
    build:
      context: ../../
      dockerfile: .docker/debug/nginx-debug.Dockerfile
    container_name: nginx-debug
    ports:
      - '8079:80'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ../../playback:/assets/segments:rw
    networks:
      - backend_network
      - frontend_network

volumes:
  segments:
    driver: local
  pgdata_api:
    driver: local
  pgconf_api:
    driver: local
  pglog_api:
    driver: local
  shared:
    driver: local
  node_modules_frontend:
  node_modules_frontend_upper:
  node_modules_backend:
  node_modules_backend_upper:
  node_modules_frontend_shared:
  node_modules_backend_shared:

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge
