const { REACT_APP_API_ORIGIN_URL, REACT_APP_GOOGLE_CLIENT_ID_GSI } = process.env;

const ENV = {
  API_PATH: REACT_APP_API_ORIGIN_URL ?? '',
  GOOGLE_CLIENT_ID: REACT_APP_GOOGLE_CLIENT_ID_GSI,
} as const;

export { ENV };
