enum IconName {
  ALARM = 'alarm',
  ARROW_DOWN = 'arrow-down',
  ARROW_UP = 'arrow-up',
  CAMERA = 'camera',
  COMPASS = 'compass',
  FILTER = 'filter',
  FOLLOW = 'follow',
  HISTORY = 'history',
  HOME = 'home',
  PLAY = 'play',
  SEARCH = 'search',
  SIGN_OUT = 'sign-out',
  SMILE = 'smile',
  TIME_AGO = 'time-ago',
  WATCH = 'watch',
  X_MARK = 'x-mark',
  BURGER_MENU = 'burger-menu',
  MAIN_LOGO = 'main-logo',
  BELL = 'bell',
  SETTINGS = 'settings',
  MOON = 'moon',
  ANALYTICS = 'analytics',
  MARK_AS_READ = 'mark-as-read',
  CLOSE = 'close',
  ZOOM_IN = 'zoom_in',
  ZOOM_OUT = 'zoom_out',
  ROTATE = 'rotate',
  EXCLAMATION = 'exclamation',
  INFO = 'info',
  WARNING = 'warning',
  SUCCESS = 'success',
  SEND_MESSAGE = 'send-message',
  EMOJI = 'emoji',
  TV = 'tv',
}

export { IconName };
