enum IconName {
  ALARM = 'alarm',
  ARROW_DOWN = 'arrow-down',
  ARROW_UP = 'arrow-up',
  CAMERA = 'camera',
  COMPAS = 'compas',
  FILTER = 'filter',
  FOLLOW = 'follow',
  HISTORY = 'history',
  HOME = 'home',
  PLAY = 'play',
  SEARCH = 'search',
  SIGNOUT = 'signout',
  SMILE = 'smile',
  TIMEAGO = 'timeago',
  WATCH = 'watch',
  XMARK = 'xmark',
  BURGERMENU = 'burger-menu',
  LOGOTIP = 'main-logo',
  BELL = 'bell',
  SETTINGS = 'settings',
  MOON = 'moon',
  LOGOUT = 'logout',
  ANALYTICS = 'analytics',
  CLOSE = 'close',
  SENDMESSAGE = 'send-message',
  EMOJI = 'emoji',
}

export { IconName };
