enum IconName {
  ALARM = 'alarm',
  CAMERA = 'camera',
  COMPAS = 'compas',
  FOLLOW = 'follow',
  HISTORY = 'history',
  HOME = 'home',
  SEARCH = 'search',
  SIGNOUT = 'signout',
  SMILE = 'smile',
  TIMEAGO = 'timeago',
  WATCH = 'watch',
  BURGERMENU = 'burger-menu',
  LOGOTIP = 'main-logo',
  BELL = 'bell',
  SETTINGS = 'settings',
  MOON = 'moon',
  LOGOUT = 'logout',
  EXCLAMATION = 'exclamation',
  INFO = 'info',
  WARNING = 'warning',
  SUCCESS = 'success',
}

export { IconName };
