-- AlterTable
ALTER TABLE "Video" ADD COLUMN     "duration" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "poster" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "publishedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "scheduledStreamDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
