export { getNameOf } from './typescript/typescript';
export { getValidClasses } from './dom/dom';
export { getFormValidationResolver } from './validation/validation';
export { getHowLongAgoString } from './date/date';
export { getImageUploadError } from './upload-image/upload-image';
export { getStringifiedQuery, type SerializedHttpError, serializeHttpError } from './http/http';
export { isRouteHasDefaultNavigation, isRouteHasStudioNavigation } from './routes/routes';
export { isObjectUniqueIdContainInTwoArray } from './array/is-object-unique-id-contain-intwo-array';
export { generateAbbreviatureNameUser, getUserDisplayName, getGoogleOAuthURL } from './user';
export { joinExistingValues, getRightUpdateTimeDelay } from './common/common';
export * from './video/video';
export { getEmojiCdnUrl } from './emoji/emoji';
