export { getNameOf } from './typescript/typescript';
export { getValidClasses } from './dom/dom';
export { getFormValidationResolver } from './validation/validation';
export { getHowLongAgoString } from './date/date';
export { getImageUploadError } from './upload-image/upload-image';
export { getStringifiedQuery, type SerializedHttpError, serializeHttpError } from './http/http';
export { isRouteHasDefaultNavigation, isRouteHasStudioNavigation } from './routes/routes';
export { isObjectUniqueIdContainInTwoArray } from './array/is-object-unique-id-contain-intwo-array';
export { removeItemIfExists } from './array/remove-item-if-exists.helper';
export { replaceItemIfExists } from './array/replace-item-if-exists.helper';
export { updateItemIfExists } from './array/update-item-if-exists.helper';
export { pushOrDeleteIfExists } from './array/push-or-delete-if-exists-helper';
export { generateAbbreviatureNameUser, getUserDisplayName } from './user';
export { joinExistingValues, getRightUpdateTimeDelay, createCounter, timeout } from './common/common';
export { getChannelBannerEditorSize } from './channel-banner-editor-size/get-channel-banner-editor-size';
export * from './image/image';
export * from './video/video';
export { getEmojiCdnUrl } from './emoji/emoji';
export { getDeviceCategoryByNavigator } from './device/device';
