enum AuthNotification {
  SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',
  ACCOUNT_VERIFICATION_LETTER_SENT = 'ACCOUNT_VERIFICATION_LETTER_SENT',
  PASSWORD_RESET_LETTER_SENT_SUCCESS = 'PASSWORD_RESET_LETTER_SENT_SUCCESS',
  ACCOUNT_VERIFICATION_SUCCESS = 'ACCOUNT_VERIFICATION_SUCCESS',
  PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS',
}

export { AuthNotification };
